//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtlyV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public string IdMessage { get; set; }
        public string IdSender { get; set; }
        public string IdReceiver { get; set; }
        public string Content { get; set; }
        public System.DateTime timestamp { get; set; }
        public bool IsActive { get; set; }
    
        public virtual MsUser MsUser { get; set; }
        public virtual MsUser MsUser1 { get; set; }

        public static implicit operator string(Message v)
        {
            throw new NotImplementedException();
        }
    }
}
