//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtlyV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MsTransaction()
        {
            this.TransactionDetails = new HashSet<TransactionDetail>();
        }
    
        public string IdTransaction { get; set; }
        public string IdUser { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string IdStatus { get; set; }
        public string IdPaymentMethod { get; set; }
        public string TrackingId { get; set; }
        public string IdAddress { get; set; }
    
        public virtual LtPaymentMethod LtPaymentMethod { get; set; }
        public virtual LtStatu LtStatu { get; set; }
        public virtual MsUser MsUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionDetail> TransactionDetails { get; set; }
        public virtual TrUserAddress TrUserAddress { get; set; }
    }
}
