//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtlyV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsUser
    {
        public string IdUser { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string IdGender { get; set; }
        public string IdRole { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public decimal Balance { get; set; }
    
        public virtual LtGender LtGender { get; set; }
        public virtual LtRole LtRole { get; set; }
    }
}
