//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtlyV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        public string IdTransactionDetail { get; set; }
        public string IdTransaction { get; set; }
        public string IdProduct { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
    
        public virtual MsTransaction MsTransaction { get; set; }
        public virtual MsProduct MsProduct { get; set; }
    }
}
