//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtlyV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrUserAddress
    {
        public string IdAddress { get; set; }
        public string IdUser { get; set; }
        public string Address { get; set; }
        public string AddressName { get; set; }
    
        public virtual MsUser MsUser { get; set; }
    }
}
